name: cetak_photo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  archive: ^3.4.10
  cupertino_icons: ^1.0.2
  file_picker: 6.1.1
  firebase_core: 2.25.4
  firebase_storage: 11.6.5
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  flutter_email_sender: ^6.0.2
  get: 4.6.6
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
